import type { NextPage } from 'next'
import Head from 'next/head'
import Spotify from '../../src'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: 'flex', flexDirection: 'row' }}>
          {/* Single track. */}
          <Spotify link="https://open.spotify.com/track/5ihDGnhQgMA0F0tk9fNLlA?si=4472348a63dd4f83" />
          <div style={{ width: 48 }} />
          {/* Album. */}
          <Spotify link="https://open.spotify.com/album/0fUy6IdLHDpGNwavIlhEsl?si=mTiITmlHQpaGkoivGTv8Jw" />
        </div>
      </main>
    </div>
  )
}

export default Home
